# Generated by Django 5.2.8 on 2025-11-21 12:43

import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring'), ('email', 'Email'), ('birthday', 'Birthday Reminder'), ('anniversary', 'Anniversary Reminder'), ('campaign', 'Email Campaign')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('crontab_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('task_args', models.JSONField(blank=True, default=dict)),
                ('task_kwargs', models.JSONField(blank=True, default=dict)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Asia/Kolkata')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='django_celery_beat.periodictask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry')], max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.scheduledtask')),
            ],
            options={
                'verbose_name_plural': 'Task Histories',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Asia/Kolkata')),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('birthday_reminder_enabled', models.BooleanField(default=True)),
                ('anniversary_reminder_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Preferences',
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_id'], name='tasks_sched_task_id_9deeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['status'], name='tasks_sched_status_d71648_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['schedule_time'], name='tasks_sched_schedul_3fb3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task_id'], name='tasks_taskh_task_id_99c0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['executed_at'], name='tasks_taskh_execute_7e2fab_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['status'], name='tasks_taskh_status_d42a7f_idx'),
        ),
    ]
